language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.10
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, coveralls.travis"
  - mix format --check-formatted
after_script:
  - "MIX_ENV=docs mix do deps.get, inch.report"
